// src/constants/systems.ts
const systems = [
  {
    id: 1,
    name: "CRM",
    description: "Sistema de gerenciamento de relacionamento com o cliente",
    status: "Publicado",
    managed: true,
    published: true,
    url: "/sistemas/sis01.svg",
    role: "Admin",
  },
  {
    id: 2,
    name: "Portal RH",
    description: "Sistema de Gestão de Recursos Humanos",
    status: "Não publicado",
    managed: false,
    published: false,
    url: "/sistemas/sis02.svg",
    role: "User",
  },
  {
    id: 3,
    name: "Portal RH",
    description: "Sistema de Gestão de Recursos Humanos",
    status: "Não publicado",
    managed: false,
    published: false,
    url: "/sistemas/sis03.svg",
    role: "User",
  },
  {
    id: 4,
    name: "Portal RH",
    description: "Sistema de Gestão de Recursos Humanos",
    status: "Não publicado",
    managed: false,
    published: false,
    url: "/sistemas/sis04.svg",
    role: "User",
  },
  {
    id: 5,
    name: "Portal RH",
    description: "Sistema de Gestão de Recursos Humanos",
    status: "Não publicado",
    managed: false,
    published: false,
    url: "/sistemas/sis05.svg",
    role: "User",
  },
];

export default systems;
