export interface Theme {
  "theme-type": ThemeType,
  "primary": ThemeColorConfiguration,
  "custom-attributes": ThemeCustomAttributes
}

export type ThemeType = 'light' | 'dark' | 'gov';

export interface ThemeColorConfiguration {
  "10"?: string,
  "25"?: string,
  "50"?: string,
  "100"?: string,
  "200"?: string,
  "300"?: string,
  "400"?: string,
  "500"?: string,
  "600"?: string,
  "700"?: string,
  "800"?: string,
  "900"?: string,
  "950"?: string,
}

export interface ThemeCustomAttributes {
  "font-family"?: string,
  "background"?: string,
  "border-color"?: string,
  "border-radius"?: string,
  "button-border-radius"?: string,
  "outline-button-border-color"?: string,
  "outline-button-text-color"?: string,
  "outline-button-hover-background-color"?: string,
  "outline-button-hover-border-color"?: string,
  "outline-button-hover-text-color"?: string,
  "table-border-radius"?: string,
  "table-background-color"?: string,
  "table-header-text-color"?: string,
  "table-row-color"?: string,
  "table-row-text-color"?: string,
  "table-row-hover-color"?: string,
  "paginator-value-background-color"?: string,
  "paginator-text-color"?: string,
  "paginator-button-background-color"?: string,
  "paginator-button-disabled-background-color"?: string,
  "button-background-color"?: string,
  "button-background-hover-color"?: string,
  "button-text-color"?: string,
  "badge-border-color"?: string,
  "badge-value-color"?: string,
  "input-background-color"?: string,
  "input-border-color"?: string,
  "input-text-color"?: string,
  "input-placeholder-color"?: string,
  "input-disabled-background-color"?: string,
  "input-disabled-border-color"?: string,
  "input-disabled-text-color"?: string,
  "input-disabled-placeholder-color"?: string,
  "input-focus-border-color"?: string,
  "input-focus-text-color"?: string,
  "input-focus-placeholder-color"?: string,
  "modal-background-color"?: string,
  "modal-border-color"?: string,
  "toast-background-color"?: string,
  "toast-text-color"?: string,
  "toast-border-color"?: string,
  "popover-background-color"?: string,
  "popover-border-color"?: string,
  "popover-text-color"?: string,
  "breadcrumb-item-text-color"?: string,
  "breadcrumb-item-hover-text-color"?: string,
  "breadcrumb-item-hover-background-color"?: string,
  "breadcrumb-selected-item-text-color"?: string,
  "breadcrumb-selected-item-background-color"?: string,
  "select-options-container-background-color"?: string,
  "select-options-container-border-color"?: string,
  "select-options-selected-background-color"?: string,
  "radio-selected-color"?: string,
  "radio-border-color"?: string,
  "switch-unchecked-background-color"?: string,
  "switch-unchecked-border-color"?: string,
  'switch-thumb-background-color'?: string,
  'switch-thumb-border-color'?: string,
  'switch-thumb-size'?: string,
  'switch-thumb-padding'?: string,
  'switch-checked-background-color'?: string,
  'switch-checked-border-color'?: string,
  'switch-checked-thumb-background-color'?: string,
  "menu-background-color"?: string,
  "menu-item-text-color"?: string,
  "menu-item-selected-background-color"?: string,
  "card-border-radius"?: string,
  "tree-table-background-color"?: string,
  "tree-item-text-color"?: string,
  "tree-item-hover-background-color"?: string,
  "zebra-background-1"?: string,
  "zebra-background-2"?: string,
  "text-default-color"?: string,
  "text-muted-color"?: string,
  "success"?: string,
  "success-foreground"?: string,
  "warning"?: string,
  "warning-foreground"?: string,
  "info"?: string,
  "info-foreground"?: string,
}

export interface ThemeColorPalette {
  primary: ThemeColorConfiguration,
  info: ThemeColorConfiguration,
  gray: ThemeColorConfiguration,
  error: ThemeColorConfiguration,
  warning: ThemeColorConfiguration,
  success: ThemeColorConfiguration,
}

export interface DefaultThemeColorPalette extends ThemeColorPalette {
  blue: ThemeColorConfiguration,
  purple: ThemeColorConfiguration,
  pink: ThemeColorConfiguration,
  indigo: ThemeColorConfiguration,
  yellow: ThemeColorConfiguration,
}

export interface GovbrThemeColorPalette extends ThemeColorPalette {
  red: ThemeColorConfiguration,
  blueWarmVivid: ThemeColorConfiguration,
  green: ThemeColorConfiguration,
  yellowVivid: ThemeColorConfiguration,
  goldVivid: ThemeColorConfiguration,
}