import { THEME_COLOR_PALETTE } from "./theme-color-palette.constant";
import { THEME_BASE_CUSTOM_PROPERTIES } from "./theme-abstract.constant.ts";
import { Theme } from "../theme.model.ts";

export const DARK_THEME: Theme = {
  primary: THEME_COLOR_PALETTE.primary,
  "theme-type": "dark",
  'custom-attributes': {
    ...THEME_BASE_CUSTOM_PROPERTIES,
    'background': THEME_COLOR_PALETTE.gray['950'],
    'border-color': THEME_COLOR_PALETTE.gray['700'],
    'border-radius': '0.625rem',
    'table-border-radius': '0.625rem',
    'table-background-color': THEME_COLOR_PALETTE.gray['900'],
    'table-header-text-color': THEME_COLOR_PALETTE.gray['50'],
    'table-row-color': THEME_COLOR_PALETTE.gray['800'],
    'table-row-text-color': THEME_COLOR_PALETTE.gray['50'],
    'table-row-hover-color': THEME_COLOR_PALETTE.gray['900'],
    'paginator-value-background-color': THEME_COLOR_PALETTE.gray['800'],
    'paginator-text-color': THEME_COLOR_PALETTE.gray['50'],
    'paginator-button-background-color': THEME_COLOR_PALETTE.gray['700'],
    'paginator-button-disabled-background-color': THEME_COLOR_PALETTE.gray['800'],
    'button-background-color': THEME_COLOR_PALETTE.primary['600'],
    'button-background-hover-color': THEME_COLOR_PALETTE.primary['500'],
    'button-text-color': THEME_COLOR_PALETTE.gray['25'],
    'badge-border-color': THEME_COLOR_PALETTE.gray['700'],
    'badge-value-color': THEME_COLOR_PALETTE.gray['50'],
    'input-background-color': THEME_COLOR_PALETTE.gray['900'],
    'input-border-color': THEME_COLOR_PALETTE.gray['700'],
    'input-text-color': THEME_COLOR_PALETTE.gray['50'],
    'input-placeholder-color': THEME_COLOR_PALETTE.gray['400'],
    'input-disabled-background-color': THEME_COLOR_PALETTE.gray['800'],
    'input-disabled-border-color': THEME_COLOR_PALETTE.gray['700'],
    'input-disabled-text-color': THEME_COLOR_PALETTE.gray['500'],
    'input-disabled-placeholder-color': THEME_COLOR_PALETTE.gray['600'],
    'input-focus-border-color': THEME_COLOR_PALETTE.primary['400'],
    'input-focus-text-color': THEME_COLOR_PALETTE.gray['50'],
    'input-focus-placeholder-color': THEME_COLOR_PALETTE.gray['400'],
    'modal-background-color': THEME_COLOR_PALETTE.gray['900'],
    'modal-border-color': THEME_COLOR_PALETTE.gray['700'],
    'toast-background-color': THEME_COLOR_PALETTE.gray['800'],
    'toast-text-color': THEME_COLOR_PALETTE.gray['50'],
    'toast-border-color': THEME_COLOR_PALETTE.gray['700'],
    'popover-background-color': THEME_COLOR_PALETTE.gray['800'],
    'popover-border-color': THEME_COLOR_PALETTE.gray['700'],
    'popover-text-color': THEME_COLOR_PALETTE.gray['50'],
    'breadcrumb-item-text-color': THEME_COLOR_PALETTE.gray['400'],
    'breadcrumb-item-hover-text-color': THEME_COLOR_PALETTE.gray['50'],
    'breadcrumb-item-hover-background-color': THEME_COLOR_PALETTE.gray['800'],
    'breadcrumb-selected-item-text-color': THEME_COLOR_PALETTE.gray['50'],
    'breadcrumb-selected-item-background-color': THEME_COLOR_PALETTE.gray['700'],
    'select-options-container-background-color': THEME_COLOR_PALETTE.gray['900'],
    'select-options-container-border-color': THEME_COLOR_PALETTE.gray['700'],
    'select-options-selected-background-color': THEME_COLOR_PALETTE.gray['800'],
    'radio-selected-color': THEME_COLOR_PALETTE.primary['400'],
    'radio-border-color': THEME_COLOR_PALETTE.gray['700'],
    'switch-unchecked-background-color': THEME_COLOR_PALETTE.gray['700'],
    'switch-unchecked-border-color': THEME_COLOR_PALETTE.gray['700'],
    'menu-background-color': THEME_COLOR_PALETTE.gray['900'],
    'menu-item-text-color': THEME_COLOR_PALETTE.gray['50'],
    'menu-item-selected-background-color': THEME_COLOR_PALETTE.gray['800'],
    'card-border-radius': '0.625rem',
    'tree-table-background-color': THEME_COLOR_PALETTE.gray['900'],
    'tree-item-text-color': THEME_COLOR_PALETTE.gray['50'],
    'tree-item-hover-background-color': THEME_COLOR_PALETTE.gray['800'],
    'zebra-background-1': THEME_COLOR_PALETTE.gray['900'],
    'zebra-background-2': THEME_COLOR_PALETTE.gray['800'],
    'text-default-color': THEME_COLOR_PALETTE.gray['50'],
    'text-muted-color': THEME_COLOR_PALETTE.gray['400'],
  }
} as const;
