import { Theme } from "../theme.model";
import { THEME_BASE_CUSTOM_PROPERTIES } from "./theme-abstract.constant";
import { GOV_COLOR_PALETTE } from "./theme-color-palette.constant";

export const GOV_THEME: Theme = {
  primary: GOV_COLOR_PALETTE.primary,
  "theme-type": "gov",
  'custom-attributes': {
    ...THEME_BASE_CUSTOM_PROPERTIES,
    'font-family': "'Rawline', sans-serif",
    'background': GOV_COLOR_PALETTE.gray['10'],
    'border-color': GOV_COLOR_PALETTE.gray['400'],
    'border-radius': '0.625rem',
    'table-border-radius': '0.625rem',
    'button-border-radius': '100em',
    'outline-button-border-color': GOV_COLOR_PALETTE.primary['700'],
    'outline-button-text-color': GOV_COLOR_PALETTE.primary['700'],
    'outline-button-hover-background-color': GOV_COLOR_PALETTE.primary['100'],
    'outline-button-hover-text-color': GOV_COLOR_PALETTE.primary['700'],
    'table-background-color': GOV_COLOR_PALETTE.gray['10'],
    'table-header-text-color': GOV_COLOR_PALETTE.primary['700'],
    'table-row-color': GOV_COLOR_PALETTE.gray['10'],
    'table-row-text-color': GOV_COLOR_PALETTE.gray['800'],
    'table-row-hover-color': GOV_COLOR_PALETTE.gray['50'],
    'paginator-value-background-color': GOV_COLOR_PALETTE.gray['100'],
    'paginator-text-color': GOV_COLOR_PALETTE.gray['900'],
    'paginator-button-background-color': GOV_COLOR_PALETTE.gray['50'],
    'paginator-button-disabled-background-color': GOV_COLOR_PALETTE.gray['100'],
    'button-background-color': GOV_COLOR_PALETTE.primary['700'],
    'button-background-hover-color': GOV_COLOR_PALETTE.primary['600'],
    'button-text-color': GOV_COLOR_PALETTE.gray['10'],
    'badge-border-color': GOV_COLOR_PALETTE.gray['200'],
    'badge-value-color': GOV_COLOR_PALETTE.gray['900'],
    'input-background-color': GOV_COLOR_PALETTE.gray['50'],
    'input-border-color': GOV_COLOR_PALETTE.gray['200'],
    'input-text-color': GOV_COLOR_PALETTE.gray['900'],
    'input-placeholder-color': GOV_COLOR_PALETTE.gray['500'],
    'input-disabled-background-color': GOV_COLOR_PALETTE.gray['100'],
    'input-disabled-border-color': GOV_COLOR_PALETTE.gray['200'],
    'input-disabled-text-color': GOV_COLOR_PALETTE.gray['500'],
    'input-disabled-placeholder-color': GOV_COLOR_PALETTE.gray['400'],
    'input-focus-border-color': GOV_COLOR_PALETTE.primary['600'],
    'input-focus-text-color': GOV_COLOR_PALETTE.gray['900'],
    'input-focus-placeholder-color': GOV_COLOR_PALETTE.gray['500'],
    'modal-background-color': GOV_COLOR_PALETTE.gray['50'],
    'modal-border-color': GOV_COLOR_PALETTE.gray['200'],
    'toast-background-color': GOV_COLOR_PALETTE.gray['50'],
    'toast-text-color': GOV_COLOR_PALETTE.gray['900'],
    'toast-border-color': GOV_COLOR_PALETTE.gray['200'],
    'popover-background-color': GOV_COLOR_PALETTE.gray['50'],
    'popover-border-color': GOV_COLOR_PALETTE.gray['200'],
    'popover-text-color': GOV_COLOR_PALETTE.gray['900'],
    'breadcrumb-item-text-color': GOV_COLOR_PALETTE.gray['600'],
    'breadcrumb-item-hover-text-color': GOV_COLOR_PALETTE.gray['900'],
    'breadcrumb-item-hover-background-color': GOV_COLOR_PALETTE.gray['100'],
    'breadcrumb-selected-item-text-color': GOV_COLOR_PALETTE.gray['900'],
    'breadcrumb-selected-item-background-color': GOV_COLOR_PALETTE.gray['100'],
    'select-options-container-background-color': GOV_COLOR_PALETTE.gray['50'],
    'select-options-container-border-color': GOV_COLOR_PALETTE.gray['200'],
    'select-options-selected-background-color': GOV_COLOR_PALETTE.gray['200'],
    'radio-selected-color': GOV_COLOR_PALETTE.primary['600'],
    'radio-border-color': GOV_COLOR_PALETTE.gray['200'],
    'switch-unchecked-background-color': GOV_COLOR_PALETTE.gray['10'],
    'switch-unchecked-border-color': GOV_COLOR_PALETTE.gray['100'],
    'switch-thumb-background-color': GOV_COLOR_PALETTE.gray['200'],
    'switch-thumb-border-color': GOV_COLOR_PALETTE.gray['200'],
    'switch-thumb-size': '1.25rem',
    'switch-thumb-padding': '0.125rem',
    'switch-checked-thumb-background-color': GOV_COLOR_PALETTE.primary['400'],
    'switch-checked-background-color': GOV_COLOR_PALETTE.gray['10'],
    'switch-checked-border-color': GOV_COLOR_PALETTE.gray['100'],
    'menu-background-color': GOV_COLOR_PALETTE.gray['50'],
    'menu-item-text-color': GOV_COLOR_PALETTE.gray['900'],
    'menu-item-selected-background-color': GOV_COLOR_PALETTE.gray['100'],
    'card-border-radius': '0.625rem',
    'tree-table-background-color': GOV_COLOR_PALETTE.gray['50'],
    'tree-item-text-color': GOV_COLOR_PALETTE.gray['900'],
    'tree-item-hover-background-color': GOV_COLOR_PALETTE.gray['100'],
    'zebra-background-1': GOV_COLOR_PALETTE.gray['50'],
    'zebra-background-2': GOV_COLOR_PALETTE.gray['25'],
    'text-default-color': GOV_COLOR_PALETTE.gray['900'],
    'text-muted-color': GOV_COLOR_PALETTE.gray['500'],
  }
} as const