import { Theme } from "../theme.model";
import { GOV_COLOR_PALETTE } from "./theme-color-palette.constant";

export const GOV_THEME: Theme = {
  primary: GOV_COLOR_PALETTE.primary,
  "theme-type": "gov",
  "attributes": {
    // general
    "font-family": "'Inter', sans-serif",
    "background": "#ffffff",
    "content-background-color": "#f3f4f6",
    "border-color": "#e3e8ef",
    "default-text-color": "#ffffff",
    "inverse-default-text-color": "#ffffff",
    "default-text-font-weight": "400",
    "default-button-font-size": "14px",

    // step-loader
    "step-loader-overlay-z-index": "120",
    "step-loader-overlay-background-color": "rgba(15, 23, 42, 0.45)",
    "step-loader-card-width": "420px",
    "step-loader-card-min-height": "220px",
    "step-loader-card-padding": "24px",
    "step-loader-card-radius": "12px",
    "step-loader-card-border": "1px solid var(--table-border-color)",
    "step-loader-card-background-color": "#ffffff",
    "step-loader-card-shadow": "0 24px 54px rgba(15, 23, 42, 0.14)",
    "step-loader-list-gap": "10px",
    "step-loader-item-gap": "12px",
    "step-loader-item-min-height": "28px",
    "step-loader-item-icon-size": "20px",
    "step-loader-item-icon-color-active": "var(--color-primary-500)",
    "step-loader-item-icon-color-inactive": "#94a3b8",
    "step-loader-item-font-size": "14px",
    "step-loader-item-font-weight": "600",
    "step-loader-item-line-height": "1.4",
    "step-loader-item-color-active": "var(--title-color)",
    "step-loader-item-color-inactive": "var(--description-color)",
    "step-loader-item-transition": "220ms ease",

    // highlight-loader
    "highlight-loader-gap": "12px",
    "highlight-loader-track-width-sm": "72px",
    "highlight-loader-track-height-sm": "8px",
    "highlight-loader-track-width-md": "112px",
    "highlight-loader-track-height-md": "10px",
    "highlight-loader-track-width-lg": "144px",
    "highlight-loader-track-height-lg": "12px",
    "highlight-loader-track-border": "1px solid var(--table-border-color)",
    "highlight-loader-track-radius": "9999px",
    "highlight-loader-track-background-color": "#f1f5f9",
    "highlight-loader-bar-gradient": "linear-gradient(90deg, var(--color-primary-500), var(--color-primary-300))",
    "highlight-loader-bar-shadow": "0 0 12px rgba(60, 131, 246, 0.35)",
    "highlight-loader-track-glow": "inset 0 0 0 1px rgba(255, 255, 255, 0.35)",
    "highlight-loader-logo-width-sm": "56px",
    "highlight-loader-logo-max-height-sm": "7px",
    "highlight-loader-logo-width-md": "80px",
    "highlight-loader-logo-max-height-md": "9px",
    "highlight-loader-logo-width-lg": "104px",
    "highlight-loader-logo-max-height-lg": "11px",
    "highlight-loader-logo-opacity": "0.96",
    "highlight-loader-logo-drop-shadow": "0 1px 4px rgba(15, 23, 42, 0.18)",
    "highlight-loader-message-font-size": "13px",
    "highlight-loader-message-font-weight": "600",
    "highlight-loader-message-color": "var(--description-color)",

    // layout
    "main-content-default-max-width": "1260px",
    "title-color": "#111827",
    "title-size": "24px",
    "description-color": "#6c727f",
    "description-size": "14px",
    "meta-label-color": "#94A3B8",
    "meta-value-color": "#334155",

    // table
    "table-header-filter-background-color": "#fcfdfd",
    "table-header-filter-min-height": "72px",
    "table-header-background-color": "#f9fafb",
    "table-header-text-color": "#6b7280",
    "table-header-text-size": "12px",
    "table-row-text-size": "14px",
    "table-footer-min-height": "72px",
    "table-border-color": "#e5e7eb",
    "table-icon-cell-width": "56px",

    // pagination
    "pagination-border-color": "var(--table-border-color)",
    "pagination-border": "1px solid var(--pagination-border-color)",
    "pagination-gap": "0px",
    "pagination-control-radius": "6px",
    "pagination-control-min-width": "84px",
    "pagination-control-height": "36px",
    "pagination-control-padding-inline": "14px",
    "pagination-item-min-width": "36px",
    "pagination-item-padding-inline": "10px",
    "pagination-font-size": "14px",
    "pagination-disabled-opacity": "0.6",

    // input
    "input-border-color": "#d1d5db",
    "input-height": "38px",
    "input-radius": "6px",
    "input-placeholder-color": "#6b7280",
    "input-padding-inline": "12px",
    "input-icon-size": "16px",
    "input-icon-left-offset": "12px",
    "input-padding-inline-with-icon": "40px",

    // textarea
    "textarea-min-height": "80px",
    "textarea-border-color": "var(--input-border-color)",
    "textarea-radius": "var(--input-radius)",
    "textarea-padding-block": "8px",
    "textarea-padding-inline": "var(--input-padding-inline)",
    "textarea-placeholder-color": "var(--input-placeholder-color)",
    "textarea-text-color": "var(--default-text-color)",
    "textarea-font-size": "var(--default-button-font-size)",
    "textarea-font-weight": "var(--default-text-font-weight)",

    // badge
    "badge-height": "30px",
    "badge-radius": "9999px",
    "badge-font-size": "12px",
    "badge-padding-inline": "10px",
    "badge-icon-size": "10px",
    "badge-icon-gap": "6px",
    "badge-status-published-text-color": "#01bc78",
    "badge-status-published-background-color": "rgba(16, 185, 129, 0.1)",
    "badge-status-published-border-color": "rgba(16, 185, 129, 0.3)",
    "badge-status-unpublished-text-color": "#fcb600",
    "badge-status-unpublished-background-color": "rgba(245, 158, 11, 0.1)",
    "badge-status-unpublished-border-color": "rgba(245, 158, 11, 0.2)",
    "badge-header-text-color": "#1d4ed8",
    "badge-header-background-color": "rgba(59, 130, 246, 0.2)",
    "badge-header-border-color": "rgba(59, 130, 246, 0.4)",

    // dropdown-menu
    "dropdown-background-color": "#ffffff",
    "dropdown-border-color": "var(--table-border-color)",
    "dropdown-radius": "6px",
    "dropdown-shadow": "0 10px 25px rgba(17, 24, 39, 0.12)",
    "dropdown-font-size": "12px",
    "dropdown-item-height": "32px",
    "dropdown-item-gap": "8px",
    "dropdown-item-padding-inline": "10px",
    "dropdown-item-padding-inline-inset": "32px",
    "dropdown-item-hover-background-color": "rgba(17, 24, 39, 0.04)",
    "dropdown-item-indicator-left": "10px",
    "dropdown-content-padding": "6px",
    "dropdown-min-width": "160px",
    "dropdown-icon-size": "14px",
    "dropdown-z-index": "50",
    "dropdown-slide-distance": "4px",
    "dropdown-disabled-opacity": "0.5",
    "dropdown-label-font-weight": "600",
    "dropdown-separator-color": "var(--table-border-color)",
    "dropdown-separator-margin-block": "4px",
    "dropdown-shortcut-opacity": "0.7",

    // toggle
    "toggle-width": "48px",
    "toggle-height": "24px",
    "toggle-radius": "9999px",
    "toggle-motion": "220ms ease",
    "toggle-track-background-color-active": "var(--color-primary-500)",
    "toggle-track-background-color-inactive": "#e5e7eb",
    "toggle-thumb-size-inactive": "24px",
    "toggle-thumb-size-active": "28px",
    "toggle-thumb-radius": "9999px",
    "toggle-thumb-background-color-inactive": "#ffffff",
    "toggle-thumb-background-color-active": "var(--color-primary-500)",
    "toggle-thumb-border-color-inactive": "#d1d5db",
    "toggle-icon-size": "14px",
    "toggle-icon-stroke-width": "2.75",

    // option-select
    "option-select-gap": "12px",
    "option-select-item-min-height": "40px",
    "option-select-item-padding-inline": "18px",
    "option-select-item-radius": "9999px",
    "option-select-item-border": "1px solid var(--input-border-color)",
    "option-select-item-border-color-hover": "var(--color-primary-300)",
    "option-select-item-active-border-color": "var(--color-primary-500)",
    "option-select-item-background-color": "#ffffff",
    "option-select-item-text-color": "var(--default-text-color)",
    "option-select-item-active-text-color": "var(--color-primary-500)",
    "option-select-item-active-inner-shadow": "inset 0 0 0 1px var(--color-primary-500)",
    "option-select-item-transition": "180ms ease",
    "option-select-item-active-transform": "translateY(-1px)",
    "option-select-item-disabled-opacity": "0.6",

    // request-detail
    "request-detail-page-padding-inline": "28px",
    "request-detail-header-padding-top": "36px",
    "request-detail-header-padding-bottom": "20px",
    "request-detail-header-border": "1px solid var(--table-border-color)",
    "request-detail-content-padding-top": "24px",
    "request-detail-content-padding-bottom": "24px",
    "request-detail-section-gap": "24px",
    "request-detail-content-gap": "16px",
    "request-detail-grid-gap": "24px",
    "request-detail-title-gap": "12px",
    "request-detail-title-font-weight": "600",
    "request-detail-back-button-offset-top": "2px",
    "request-detail-section-icon-size": "24px",
    "request-detail-section-title-font-size": "20px",
    "request-detail-card-padding": "24px",
    "request-detail-card-content-gap": "20px",
    "request-detail-card-border": "1px solid var(--table-border-color)",
    "request-detail-card-radius": "12px",
    "request-detail-control-radius": "8px",
    "request-detail-details-grid-columns": "2",
    "request-detail-details-grid-min-width": "360px",
    "request-detail-info-grid-columns": "2",
    "request-detail-info-card-min-width": "360px",
    "request-detail-system-card-min-height": "160px",
    "request-detail-hierarchy-empty-min-height": "56px",
    "request-detail-status-icon-box-size": "56px",
    "request-detail-status-icon-box-radius": "9999px",
    "request-detail-status-icon-size": "24px",
    "request-detail-status-title-font-size": "20px",
    "request-detail-status-chip-height": "32px",
    "request-detail-status-chip-padding-inline": "16px",
    "request-detail-status-chip-radius": "9999px",
    "request-detail-status-chip-font-size": "14px",
    "request-detail-progress-gap": "10px",
    "request-detail-progress-height": "14px",
    "request-detail-progress-radius": "9999px",
    "request-detail-progress-track-color": "#e5e7eb",
    "request-detail-progress-transition": "280ms ease",
    "request-detail-status-feedback-min-height": "52px",
    "request-detail-action-button-padding-inline": "16px",
    "request-detail-info-icon-box-size": "40px",
    "request-detail-info-icon-box-radius": "8px",
    "request-detail-info-icon-size": "20px",
    "request-detail-info-label-color": "#6b7280",
    "request-detail-info-label-font-size": "12px",
    "request-detail-info-value-font-size": "14px",
    "request-detail-system-name-font-size": "22px",
    "request-detail-copy-button-size": "24px",
    "request-detail-copy-icon-size": "16px",
    "request-detail-empty-state-gap": "8px",
    "request-detail-file-row-gap": "12px",
    "request-detail-file-row-padding": "12px",
    "request-detail-file-icon-gap": "12px",
    "request-detail-file-icon-box-size": "32px",
    "request-detail-file-row-background-color": "#f8fafc",
    "request-detail-attachments-grid-columns": "2",
    "request-detail-attachments-card-min-width": "320px",
    "request-detail-modal-padding": "24px",
    "request-detail-modal-title-font-size": "20px",
    "request-detail-modal-textarea-min-height": "112px",
    "request-status-tone-primary-text-color": "#1d4ed8",
    "request-status-tone-primary-surface-color": "rgba(59, 130, 246, 0.16)",
    "request-status-tone-primary-solid-color": "var(--color-primary-500)",
    "request-status-tone-success-text-color": "#047857",
    "request-status-tone-success-surface-color": "rgba(16, 185, 129, 0.16)",
    "request-status-tone-success-solid-color": "#10b981",
    "request-status-tone-danger-text-color": "#b91c1c",
    "request-status-tone-danger-surface-color": "rgba(239, 68, 68, 0.16)",
    "request-status-tone-danger-solid-color": "#ef4444",
    "request-status-tone-neutral-text-color": "#4b5563",
    "request-status-tone-neutral-surface-color": "rgba(107, 114, 128, 0.16)",
    "request-status-tone-neutral-solid-color": "#6b7280",

    // request-access
    "request-access-page-padding-inline": "28px",
    "request-access-page-padding-top": "24px",
    "request-access-page-padding-bottom": "24px",
    "request-access-header-padding-top": "36px",
    "request-access-header-padding-bottom": "24px",
    "request-access-header-gap": "12px",
    "request-access-header-border": "1px solid var(--table-border-color)",
    "request-access-content-gap": "0px",
    "request-access-step-content-gap": "32px",
    "request-access-stepper-border": "1px solid var(--table-border-color)",
    "request-access-stepper-radius": "12px",
    "request-access-stepper-padding-inline": "44px",
    "request-access-stepper-padding-block": "24px",
    "request-access-stepper-items-gap": "20px",
    "request-access-stepper-item-gap": "8px",
    "request-access-stepper-item-inactive-opacity": "0.4",
    "request-access-stepper-item-active-opacity": "1",
    "request-access-stepper-item-completed-opacity": "1",
    "request-access-stepper-number-size": "32px",
    "request-access-stepper-number-radius": "9999px",
    "request-access-stepper-number-border-inactive": "1px solid #e2e8f0",
    "request-access-stepper-number-border-active": "1px solid var(--color-primary-500)",
    "request-access-stepper-number-border-completed": "1px solid #22c55e",
    "request-access-stepper-number-background-inactive": "transparent",
    "request-access-stepper-number-background-active": "var(--color-primary-500)",
    "request-access-stepper-number-background-completed": "#22c55e",
    "request-access-stepper-number-color-inactive": "#94a3b8",
    "request-access-stepper-number-color-active": "var(--inverse-default-text-color)",
    "request-access-stepper-number-color-completed": "var(--inverse-default-text-color)",
    "request-access-stepper-number-shadow-active": "0 8px 18px rgba(60, 131, 246, 0.24)",
    "request-access-stepper-check-icon-size": "14px",
    "request-access-stepper-title-font-size": "14px",
    "request-access-stepper-title-font-weight": "700",
    "request-access-stepper-title-color-completed": "#22c55e",
    "request-access-stepper-description-font-size": "10px",
    "request-access-stepper-description-color": "#64748b",
    "request-access-stepper-item-min-width": "220px",
    "request-access-step-panel-border": "1px solid var(--table-border-color)",
    "request-access-step-panel-radius": "12px",
    "request-access-step-panel-header-padding": "32px",
    "request-access-step-panel-surface-color": "#f8fafc",
    "request-access-step-panel-divider": "1px solid var(--table-border-color)",
    "request-access-step-panel-title-font-size": "20px",
    "request-access-step-panel-title-font-weight": "700",
    "request-access-step-panel-footer-padding": "32px",
    "request-access-step-panel-footer-gap": "12px",
    "request-access-step-panel-action-padding-inline": "16px",
    "request-access-step-panel-action-radius": "8px",
    "request-access-step-panel-action-primary-border": "0",
    "request-access-step-panel-action-content-gap": "8px",
    "request-access-step-panel-action-icon-size": "14px",
    "request-access-system-step-padding": "32px",
    "request-access-system-step-section-gap": "24px",
    "request-access-system-step-search-height": "40px",
    "request-access-system-step-grid-columns": "2",
    "request-access-system-step-grid-columns-mobile": "1",
    "request-access-system-step-grid-gap": "16px",
    "request-access-system-step-card-min-width": "320px",
    "request-access-system-step-card-padding": "16px",
    "request-access-system-step-card-gap": "12px",
    "request-access-system-step-card-radius": "12px",
    "request-access-system-step-card-border-inactive": "1px solid #f1f5f9",
    "request-access-system-step-card-border-active": "1px solid var(--color-primary-500)",
    "request-access-system-step-card-background-inactive": "#f8fafc",
    "request-access-system-step-card-background-active": "rgba(60, 131, 246, 0.05)",
    "request-access-system-step-card-main-gap": "16px",
    "request-access-system-step-icon-box-size": "40px",
    "request-access-system-step-icon-box-radius": "8px",
    "request-access-system-step-icon-box-background-inactive": "#e2e8f0",
    "request-access-system-step-icon-box-background-active": "rgba(60, 131, 246, 0.2)",
    "request-access-system-step-icon-color-inactive": "#64748b",
    "request-access-system-step-icon-color-active": "var(--color-primary-500)",
    "request-access-system-step-icon-size": "20px",
    "request-access-system-step-name-font-size": "16px",
    "request-access-system-step-name-font-weight": "600",
    "request-access-system-step-name-color-inactive": "#334155",
    "request-access-system-step-name-color-active": "var(--title-color)",
    "request-access-system-step-selected-indicator-size": "24px",
    "request-access-system-step-selected-indicator-radius": "9999px",
    "request-access-system-step-selected-icon-size": "14px",
    "request-access-justification-gap": "24px",
    "request-access-justification-textarea-min-height": "112px",
    "request-access-justification-attachments-gap": "32px",
    "request-access-justification-title-font-size": "14px",
    "request-access-justification-grid-gap": "16px",
    "request-access-justification-card-min-width": "320px",
    "request-access-justification-card-padding": "16px",
    "request-access-justification-card-gap": "12px",
    "request-access-justification-card-radius": "12px",
    "request-access-justification-card-border": "1px solid var(--table-border-color)",
    "request-access-justification-card-border-empty": "1px dashed var(--request-access-justification-empty-border-color)",
    "request-access-justification-card-background": "#ffffff",
    "request-access-justification-dropzone-padding": "16px",
    "request-access-justification-dropzone-radius": "10px",
    "request-access-justification-dropzone-border": "2px dashed var(--request-access-justification-empty-border-color)",
    "request-access-justification-dropzone-background": "#f8fafc",
    "request-access-justification-dropzone-icon-size": "18px",
    "request-access-justification-dropzone-icon-color": "#64748b",
    "request-access-justification-dropzone-text-size": "13px",
    "request-access-justification-dropzone-text-color": "#334155",
    "request-access-justification-dropzone-hint-size": "12px",
    "request-access-justification-file-list-gap": "8px",
    "request-access-justification-file-item-padding": "10px",
    "request-access-justification-file-item-radius": "8px",
    "request-access-justification-file-item-border": "1px solid #dbeafe",
    "request-access-justification-file-item-background": "#eff6ff",
    "request-access-justification-file-name-size": "13px",
    "request-access-justification-file-meta-size": "11px",
    "request-access-justification-remove-button-size": "24px",
    "request-access-justification-remove-icon-size": "18px",
    "request-access-justification-empty-border-color": "#e2e8f0",

    // system-form
    "system-form-page-padding-inline": "28px",
    "system-form-page-padding-top": "24px",
    "system-form-page-padding-bottom": "24px",
    "system-form-header-padding-top": "36px",
    "system-form-header-padding-bottom": "24px",
    "system-form-header-container-gap": "12px",
    "system-form-header-container-border": "1px solid var(--table-border-color)",
    "system-form-header-gap": "16px",
    "system-form-header-main-gap": "12px",
    "system-form-heading-content-gap": "8px",
    "system-form-title-gap": "8px",
    "system-form-control-border": "1px solid var(--table-border-color)",
    "system-form-control-radius": "8px",
    "system-form-card-radius": "12px",
    "system-form-card-border": "1px solid var(--table-border-color)",
    "system-form-card-shadow": "0 4px 14px rgba(15, 23, 42, 0.04)",
    "system-form-header-min-height": "72px",
    "system-form-header-padding-inline": "32px",
    "system-form-header-background-color": "#f9fafb",
    "system-form-header-border": "1px solid var(--table-border-color)",
    "system-form-step-gap": "32px",
    "system-form-step-text-gap": "10px",
    "system-form-step-font-size": "14px",
    "system-form-step-text-color-active": "var(--color-primary-500)",
    "system-form-step-text-color-inactive": "#9ca3af",
    "system-form-step-active-shadow": "inset 0 -3px 0 0 var(--color-primary-500)",
    "system-form-step-number-size": "24px",
    "system-form-step-number-radius": "9999px",
    "system-form-step-number-font-size": "14px",
    "system-form-step-number-background-color-inactive": "#e5e7eb",
    "system-form-step-number-color-inactive": "#6b7280",
    "system-form-content-padding": "32px",
    "system-form-form-row-gap": "30px",
    "system-form-form-column-gap": "32px",
    "system-form-field-min-width": "280px",
    "system-form-field-gap": "8px",
    "system-form-field-label-font-size": "14px",
    "system-form-required-color": "#ef4444",
    "system-form-input-border-color": "#d1d5db",
    "system-form-input-text-color": "#0f172a",
    "system-form-textarea-min-height": "104px",
    "system-form-textarea-padding-block": "10px",
    "system-form-counter-font-size": "12px",
    "system-form-error-font-size": "12px",
    "system-form-toggle-row-gap": "48px",
    "system-form-toggle-row-padding-top": "32px",
    "system-form-toggle-row-border": "1px solid var(--table-border-color)",
    "system-form-toggle-min-width": "280px",
    "system-form-actions-padding-top": "24px",
    "system-form-action-button-padding-inline": "16px",
    "system-form-continue-icon-size": "14px",
    "system-form-footer-gap": "12px",
    "system-form-footer-padding-block": "16px",
    "system-form-footer-border": "1px solid var(--table-border-color)",

    // attachment-configuration-form
    "attachment-configuration-section-gap": "24px",
    "attachment-configuration-title-font-size": "20px",
    "attachment-configuration-title-font-weight": "600",
    "attachment-configuration-surface-background-color": "#f9fafb",
    "attachment-configuration-border": "1px solid var(--table-border-color)",
    "attachment-configuration-radius": "8px",
    "attachment-configuration-surface-padding": "24px",
    "attachment-configuration-form-gap": "24px",
    "attachment-configuration-top-column-min-width": "280px",
    "attachment-configuration-top-row-gap": "24px",
    "attachment-configuration-field-gap": "8px",
    "attachment-configuration-description-min-height": "104px",
    "attachment-configuration-icon-row-gap": "12px",
    "attachment-configuration-icon-preview-size": "36px",
    "attachment-configuration-icon-preview-background-color": "#eff6ff",
    "attachment-configuration-icon-size": "18px",
    "attachment-configuration-extension-picker-gap": "8px",
    "attachment-configuration-extension-option-height": "32px",
    "attachment-configuration-extension-option-padding-inline": "12px",
    "attachment-configuration-toggle-padding-top": "12px",
    "attachment-configuration-import-export-gap": "16px",
    "attachment-configuration-action-button-padding-inline": "16px",
    "attachment-configuration-button-content-gap": "8px",
    "attachment-configuration-button-icon-size": "16px",
    "attachment-configuration-empty-state-padding": "24px",
    "attachment-configuration-list-gap": "16px",
    "attachment-configuration-list-max-columns": "3",
    "attachment-configuration-card-min-width": "260px",
    "attachment-configuration-card-max-width": "360px",
    "attachment-configuration-card-padding": "20px",
    "attachment-configuration-card-gap": "16px",
    "attachment-configuration-delete-button-size": "24px",
    "attachment-configuration-card-name-font-size": "16px",
    "attachment-configuration-badge-wrap-padding-bottom": "12px",
    "attachment-configuration-optional-badge-background-color": "#f3f4f6",
    "attachment-configuration-optional-badge-text-color": "#1f2937",
    "attachment-configuration-card-extensions-gap": "12px",
    "attachment-configuration-extension-label-color": "#6b7280",
    "attachment-configuration-extension-badge-height": "20px",
    "attachment-configuration-extension-badge-radius": "9999px",
    "attachment-configuration-extension-badge-padding-inline": "8px",
    "attachment-configuration-extension-badge-background-color": "#f3f4f6",
    "attachment-configuration-extension-badge-text-color": "#6b7280",
    "attachment-configuration-extension-badge-font-size": "10px",
    "attachment-configuration-dialog-list-padding-inline-start": "20px",

    // dialog
    "dialog-z-index": "71",
    "dialog-overlay-z-index": "70",
    "dialog-overlay-background-color": "rgba(15, 23, 42, 0.64)",
    "dialog-width": "calc(100% - 2rem)",
    "dialog-max-width": "560px",
    "dialog-gap": "20px",
    "dialog-border": "1px solid var(--table-border-color)",
    "dialog-background-color": "var(--background)",
    "dialog-padding": "24px",
    "dialog-shadow": "0 20px 45px rgba(15, 23, 42, 0.2)",
    "dialog-radius": "12px",
    "dialog-close-offset-inline": "16px",
    "dialog-close-offset-block": "16px",
    "dialog-close-size": "28px",
    "dialog-close-radius": "8px",
    "dialog-close-border": "1px solid var(--table-border-color)",
    "dialog-close-background-color": "var(--background)",
    "dialog-close-hover-background-color": "#f8fafc",
    "dialog-close-icon-color": "#64748b",
    "dialog-close-icon-size": "16px",
    "dialog-header-gap": "8px",
    "dialog-title-color": "var(--title-color)",
    "dialog-title-font-size": "20px",
    "dialog-title-font-weight": "700",
    "dialog-description-color": "var(--description-color)",
    "dialog-description-font-size": "14px",
    "dialog-body-gap": "16px",
    "dialog-surface-border": "1px solid var(--table-border-color)",
    "dialog-surface-radius": "10px",
    "dialog-surface-background-color": "#f8fafc",
    "dialog-surface-padding": "14px",
    "dialog-surface-gap": "12px",
    "dialog-surface-main-gap": "4px",
    "dialog-surface-title-color": "#0f172a",
    "dialog-surface-title-font-size": "14px",
    "dialog-surface-title-font-weight": "600",
    "dialog-surface-description-color": "#64748b",
    "dialog-surface-description-font-size": "12px",
    "dialog-footer-gap": "10px",
    "dialog-footer-padding-top": "4px",
    "dialog-action-height": "36px",
    "dialog-action-padding-inline": "16px",
    "dialog-action-radius": "8px",
    "dialog-action-border": "1px solid var(--table-border-color)",
    "dialog-action-content-gap": "8px",

    // login
    "login-layout-columns": "1.3fr 1fr",
    "login-visual-border": "1px solid var(--table-border-color)",
    "login-visual-background-color": "#f8fafc",
    "login-panel-padding-inline": "48px",
    "login-panel-padding-block": "32px",
    "login-panel-max-width": "440px",
    "login-panel-content-gap": "28px",
    "login-heading-gap": "10px",
    "login-title-font-size": "32px",
    "login-title-font-weight": "700",
    "login-action-height": "40px",
    "login-action-padding-inline": "20px",
    "login-action-radius": "8px",
    "login-breakpoint-stack": "1024px",
    "login-visual-mobile-height": "45vh",

    // invitation
    "invitation-page-min-height": "calc(var(--mobile-vh, 1vh) * 100)",
    "invitation-page-padding-inline": "16px",
    "invitation-page-padding-block": "70px",
    "invitation-page-background-color": "#f3f7f8",
    "invitation-card-max-width": "480px",
    "invitation-card-radius": "8px",
    "invitation-card-border": "1px solid #e2e8f0",
    "invitation-card-shadow": "0 20px 25px -5px rgba(17, 24, 39, 0.12), 0 8px 10px -6px rgba(17, 24, 39, 0.12)",
    "invitation-card-background-color": "#ffffff",
    "invitation-body-padding-inline": "32px",
    "invitation-body-padding-top": "40px",
    "invitation-body-padding-bottom": "32px",
    "invitation-body-gap": "32px",
    "invitation-brand-gap": "8px",
    "invitation-brand-icon-box-size": "40px",
    "invitation-brand-icon-box-radius": "8px",
    "invitation-brand-icon-box-background-color": "var(--color-primary-500)",
    "invitation-brand-icon-size": "20px",
    "invitation-brand-title-color": "#0f172a",
    "invitation-brand-title-font-size": "24px",
    "invitation-brand-title-font-weight": "700",
    "invitation-brand-title-letter-spacing": "-0.025em",
    "invitation-hero-height": "192px",
    "invitation-hero-radius": "8px",
    "invitation-content-gap": "12px",
    "invitation-title-color": "#0f172a",
    "invitation-title-font-size": "24px",
    "invitation-title-font-weight": "700",
    "invitation-title-line-height": "1.25",
    "invitation-description-color": "#475569",
    "invitation-description-font-size": "16px",
    "invitation-description-line-height": "1.625",
    "invitation-description-max-width": "392px",
    "invitation-details-padding": "21px",
    "invitation-details-gap": "16px",
    "invitation-details-radius": "8px",
    "invitation-details-background-color": "#f8fafc",
    "invitation-details-border": "1px solid #f1f5f9",
    "invitation-detail-divider-color": "#e2e8f0",
    "invitation-detail-label-color": "#64748b",
    "invitation-detail-label-font-size": "14px",
    "invitation-detail-label-font-weight": "500",
    "invitation-detail-value-color": "#0f172a",
    "invitation-detail-value-font-size": "14px",
    "invitation-detail-value-font-weight": "600",
    "invitation-detail-icon-size": "14px",
    "invitation-detail-value-gap": "6px",
    "invitation-actions-gap": "12px",
    "invitation-primary-action-min-height": "52px",
    "invitation-primary-action-radius": "8px",
    "invitation-primary-action-font-size": "16px",
    "invitation-primary-action-font-weight": "600",
    "invitation-secondary-action-min-height": "32px",
    "invitation-secondary-action-color": "#475569",
    "invitation-secondary-action-font-size": "14px",
    "invitation-secondary-action-font-weight": "500",
    "invitation-footer-padding-inline": "32px",
    "invitation-footer-padding-block": "24px",
    "invitation-footer-background-color": "#f8fafc",
    "invitation-footer-border-top": "1px solid #f1f5f9",
    "invitation-footer-color": "#94a3b8",
    "invitation-footer-font-size": "12px",
    "invitation-footer-line-height": "1.33",
    "invitation-breakpoint-stack": "640px",

    // header
    "header-padding-inline": "20px",
    "header-padding-inline-mobile": "12px",
    "header-nav-gap": "16px",
    "header-brand-gap": "12px",
    "header-brand-min-width": "220px",
    "header-actions-gap": "12px",
    "header-control-size": "40px",
    "header-control-height": "40px",
    "header-control-radius": "10px",
    "header-control-border": "1px solid var(--table-border-color)",
    "header-control-background-color": "#ffffff",
    "header-control-hover-background-color": "#f8fafc",
    "header-control-icon-color": "#334155",
    "header-control-icon-size": "18px",
    "header-control-padding-inline": "12px",
    "header-control-padding-inline-mobile": "8px",
    "header-panel-shadow": "0 12px 32px rgba(15, 23, 42, 0.16)",
    "header-title-color": "#111827",
    "header-subtitle-color": "#64748b",
    "header-subtitle-font-size": "12px",
    "header-divider-size": "1px",
    "header-logo-gap": "10px",
    "header-logo-icon-box-size": "36px",
    "header-logo-icon-box-radius": "10px",
    "header-logo-icon-box-background-color": "rgba(60, 131, 246, 0.12)",
    "header-logo-icon-size": "20px",
    "header-logo-title-color": "#0f172a",
    "header-logo-title-font-size": "20px",
    "header-logo-title-font-weight": "700",
    "header-logo-title-letter-spacing": "0.01em",
    "header-theme-menu-width": "160px",
    "header-theme-item-gap": "8px",
    "header-theme-item-active-font-weight": "700",
    "header-user-trigger-gap": "10px",
    "header-user-identity-gap": "4px",
    "header-user-name-color": "#0f172a",
    "header-user-name-font-size": "14px",
    "header-user-name-font-weight": "700",
    "header-user-email-color": "#64748b",
    "header-user-email-font-size": "12px",
    "header-user-email-max-width": "180px",
    "header-user-chevron-size": "16px",
    "header-user-chevron-color": "#64748b",
    "header-user-menu-width": "260px",
    "header-user-menu-header-gap": "4px",
    "header-user-menu-item-gap": "8px",
    "header-user-menu-item-icon-size": "16px",
    "header-avatar-size": "36px",
    "header-avatar-radius": "10px",
    "header-avatar-border": "1px solid #dbe4ef",
    "header-notification-badge-offset-inline": "-2px",
    "header-notification-badge-offset-block": "-3px",
    "header-notification-badge-size": "18px",
    "header-notification-badge-radius": "9999px",
    "header-notification-badge-padding-inline": "5px",
    "header-notification-badge-font-size": "10px",
    "header-notification-badge-font-weight": "700",
    "header-notification-badge-border": "1px solid #ffffff",
    "header-notification-panel-width": "360px",
    "header-notification-panel-max-height": "420px",
    "header-notification-panel-padding": "16px",
    "header-notification-header-gap": "8px",
    "header-notification-title-font-size": "16px",
    "header-notification-title-font-weight": "700",
    "header-notification-divider-gap": "12px",
    "header-notification-list-gap": "10px",
    "header-notification-item-gap": "12px",
    "header-notification-item-padding": "10px",
    "header-notification-item-border": "1px solid #e2e8f0",
    "header-notification-item-radius": "10px",
    "header-notification-item-background-color": "#f8fafc",
    "header-notification-item-font-size": "13px",
    "header-notification-item-actions-gap": "8px",
    "header-notification-item-icon-size": "16px",
    "header-notification-open-size": "28px",
    "header-notification-open-radius": "8px",

    // dashboard-layout
    "size-layout-header": "64px",
    "size-layout-sidebar": "304px",
    "size-layout-sidebar-collapsed": "80px",
    "space-layout-sidebar-items": "16px",
    "border-layout-default": "1px solid var(--border-color)",
    "motion-layout-default": "220ms ease",
    
    // sidebar
    "sidebar-background-color": "#ffffff",
    "sidebar-item-color": "#677389",
    "sidebar-item-selected-color": GOV_COLOR_PALETTE.primary['500']!,
    "sidebar-item-hover-color": "#ecf2fd",
    "sidebar-section-gap": "16px",
    "sidebar-section-title-padding-inline": "16px",
    "sidebar-section-title-padding-block": "8px",
    "sidebar-section-title-color": "#94a3b8",
    "sidebar-section-title-font-size": "12px",
    "sidebar-section-title-font-weight": "700",
    "sidebar-tooltip-offset": "8px",
    "sidebar-tooltip-offset-block": "50%",
    "sidebar-tooltip-padding-inline": "12px",
    "sidebar-tooltip-padding-block": "8px",
    "sidebar-tooltip-font-size": "12px",
    "sidebar-tooltip-font-weight": "600",
    "sidebar-tooltip-text-color": "var(--title-color)",
    "sidebar-tooltip-background-color": "#ffffff",
    "sidebar-tooltip-border": "1px solid var(--table-border-color)",
    "sidebar-tooltip-radius": "8px",
    "sidebar-tooltip-shadow": "0 8px 20px rgba(15, 23, 42, 0.14)",
  }
} as const
