import { THEME_COLOR_PALETTE } from "./theme-color-palette.constant";
import { Theme } from "../theme.model.ts";

export const LIGHT_THEME: Theme = {
  primary: THEME_COLOR_PALETTE.primary,
  "theme-type": "light",
  "attributes": {
    // general
    "font-family": "'Inter', sans-serif",
    "background": "#ffffff",
    "content-background-color": "#f3f4f6",
    "border-color": "#e3e8ef",
    "default-text-color": "#111827",
    "inverse-default-text-color": "#ffffff",
    "default-text-font-weight": "400",
    "default-button-font-size": "14px",

    // layout
    "main-content-default-max-width": "1260px",
    "title-color": "#111827",
    "title-size": "24px",
    "description-color": "#6c727f",
    "description-size": "14px",
    "meta-label-color": "#94A3B8",
    "meta-value-color": "#334155",

    // table
    "table-header-filter-background-color": "#fcfdfd",
    "table-header-filter-min-height": "72px",
    "table-header-background-color": "#f9fafb",
    "table-header-text-color": "#6b7280",
    "table-header-text-size": "12px",
    "table-row-text-size": "14px",
    "table-footer-min-height": "72px",
    "table-border-color": "#e5e7eb",
    "table-icon-cell-width": "56px",

    // pagination
    "pagination-border-color": "var(--table-border-color)",
    "pagination-border": "1px solid var(--pagination-border-color)",
    "pagination-gap": "0px",
    "pagination-control-radius": "6px",
    "pagination-control-min-width": "84px",
    "pagination-control-height": "36px",
    "pagination-control-padding-inline": "14px",
    "pagination-item-min-width": "36px",
    "pagination-item-padding-inline": "10px",
    "pagination-font-size": "14px",
    "pagination-disabled-opacity": "0.6",

    // input
    "input-border-color": "#d1d5db",
    "input-height": "38px",
    "input-radius": "6px",
    "input-placeholder-color": "#6b7280",
    "input-padding-inline": "12px",
    "input-icon-size": "16px",
    "input-icon-left-offset": "12px",
    "input-padding-inline-with-icon": "40px",

    // textarea
    "textarea-min-height": "80px",
    "textarea-border-color": "var(--input-border-color)",
    "textarea-radius": "var(--input-radius)",
    "textarea-padding-block": "8px",
    "textarea-padding-inline": "var(--input-padding-inline)",
    "textarea-placeholder-color": "var(--input-placeholder-color)",
    "textarea-text-color": "var(--default-text-color)",
    "textarea-font-size": "var(--default-button-font-size)",
    "textarea-font-weight": "var(--default-text-font-weight)",

    // badge
    "badge-height": "30px",
    "badge-radius": "9999px",
    "badge-font-size": "12px",
    "badge-padding-inline": "10px",
    "badge-icon-size": "10px",
    "badge-icon-gap": "6px",
    // badge - systems list feature
    "badge-status-published-text-color": "#01bc78",
    "badge-status-published-background-color": "rgba(16, 185, 129, 0.1)",
    "badge-status-published-border-color": "rgba(16, 185, 129, 0.3)",
    "badge-status-unpublished-text-color": "#fcb600",
    "badge-status-unpublished-background-color": "rgba(245, 158, 11, 0.1)",
    "badge-status-unpublished-border-color": "rgba(245, 158, 11, 0.2)",
    // badge - common
    "badge-header-text-color": "#1d4ed8",
    "badge-header-background-color": "rgba(59, 130, 246, 0.2)",
    "badge-header-border-color": "rgba(59, 130, 246, 0.4)",

    // dropdown-menu
    "dropdown-background-color": "#ffffff",
    "dropdown-border-color": "var(--table-border-color)",
    "dropdown-radius": "6px",
    "dropdown-shadow": "0 10px 25px rgba(17, 24, 39, 0.12)",
    "dropdown-font-size": "12px",
    "dropdown-item-height": "32px",
    "dropdown-item-gap": "8px",
    "dropdown-item-padding-inline": "10px",
    "dropdown-item-padding-inline-inset": "32px",
    "dropdown-item-hover-background-color": "rgba(17, 24, 39, 0.04)",
    "dropdown-item-indicator-left": "10px",
    "dropdown-content-padding": "6px",
    "dropdown-min-width": "160px",
    "dropdown-icon-size": "14px",
    "dropdown-z-index": "50",
    "dropdown-slide-distance": "4px",
    "dropdown-disabled-opacity": "0.5",
    "dropdown-label-font-weight": "600",
    "dropdown-separator-color": "var(--table-border-color)",
    "dropdown-separator-margin-block": "4px",
    "dropdown-shortcut-opacity": "0.7",

    // toggle
    "toggle-width": "48px",
    "toggle-height": "24px",
    "toggle-radius": "9999px",
    "toggle-motion": "220ms ease",
    "toggle-track-background-color-active": "var(--color-primary-500)",
    "toggle-track-background-color-inactive": "#e5e7eb",
    "toggle-thumb-size-inactive": "24px",
    "toggle-thumb-size-active": "28px",
    "toggle-thumb-radius": "9999px",
    "toggle-thumb-background-color-inactive": "#ffffff",
    "toggle-thumb-background-color-active": "var(--color-primary-500)",
    "toggle-thumb-border-color-inactive": "#d1d5db",
    "toggle-icon-size": "14px",
    "toggle-icon-stroke-width": "2.75",

    // system-detail
    "system-detail-page-padding-inline": "28px",
    "system-detail-header-padding-top": "36px",
    "system-detail-header-padding-bottom": "24px",
    "system-detail-header-border-width": "1px",
    "system-detail-header-container-gap": "12px",
    "system-detail-header-gap": "16px",
    "system-detail-header-main-gap": "12px",
    "system-detail-heading-content-gap": "8px",
    "system-detail-title-gap": "8px",
    "system-detail-status-badge-font-size": "12px",
    "system-detail-status-badge-offset-top": "2px",
    "system-detail-header-actions-gap": "8px",
    "system-detail-header-action-gap": "8px",
    "system-detail-header-action-padding-inline": "12px",
    "system-detail-control-border-width": "1px",
    "system-detail-control-radius": "8px",
    "system-detail-content-padding-top": "24px",
    "system-detail-content-padding-bottom": "24px",
    "system-detail-sections-gap": "32px",
    "system-detail-section-heading-to-content-gap": "16px",
    "system-detail-section-title-gap": "8px",
    "system-detail-section-icon-size": "20px",
    "system-detail-section-title-font-size": "20px",
    "system-detail-section-link-font-size": "16px",
    "system-detail-section-title-font-weight": "600",
    "system-detail-card-padding": "24px",
    "system-detail-card-radius": "12px",
    "system-detail-card-content-gap": "24px",
    "system-detail-grid-column-gap": "24px",
    "system-detail-grid-row-gap": "24px",
    "system-detail-general-grid-columns": "4",
    "system-detail-general-grid-columns-mobile": "2",
    "system-detail-general-grid-columns-small": "1",
    "system-detail-field-gap": "6px",
    "system-detail-field-font-size": "14px",
    "system-detail-field-min-height": "20px",
    "system-detail-field-label-color": "#6b7280",
    "system-detail-border-color": "#e5e7eb",
    "system-detail-attachments-grid-columns": "2",
    "system-detail-attachments-grid-columns-mobile": "1",
    "system-detail-attachments-grid-gap": "16px",
    "system-detail-attachment-padding": "16px",
    "system-detail-attachment-content-gap": "16px",
    "system-detail-attachment-main-gap": "12px",
    "system-detail-attachment-icon-box-size": "40px",
    "system-detail-attachment-icon-box-radius": "8px",
    "system-detail-attachment-icon-size": "20px",
    "system-detail-attachment-icon-background-color": "#eff6ff",
    "system-detail-attachment-meta-gap": "6px",
    "system-detail-attachment-dot-line-height": "1",
    "system-detail-attachment-info-button-size": "24px",
    "system-detail-attachment-popover-width": "320px",
    "system-detail-popover-content-gap": "12px",
    "system-detail-role-item-gap": "8px",
    "system-detail-role-item-min-height": "40px",
    "system-detail-role-indent-size": "20px",
    "system-detail-role-expand-size": "24px",
    "system-detail-role-icon-box-size": "24px",

    // system-form
    "system-form-page-padding-inline": "28px",
    "system-form-page-padding-top": "24px",
    "system-form-page-padding-bottom": "24px",
    "system-form-header-padding-top": "36px",
    "system-form-header-padding-bottom": "24px",
    "system-form-header-container-gap": "12px",
    "system-form-header-container-border": "1px solid var(--table-border-color)",
    "system-form-header-gap": "16px",
    "system-form-header-main-gap": "12px",
    "system-form-heading-content-gap": "8px",
    "system-form-title-gap": "8px",
    "system-form-control-border": "1px solid var(--table-border-color)",
    "system-form-control-radius": "8px",
    "system-form-card-radius": "12px",
    "system-form-card-border": "1px solid var(--table-border-color)",
    "system-form-card-shadow": "0 4px 14px rgba(15, 23, 42, 0.04)",
    "system-form-header-min-height": "72px",
    "system-form-header-padding-inline": "32px",
    "system-form-header-background-color": "#f9fafb",
    "system-form-header-border": "1px solid var(--table-border-color)",
    "system-form-step-gap": "32px",
    "system-form-step-text-gap": "10px",
    "system-form-step-font-size": "14px",
    "system-form-step-text-color-active": "var(--color-primary-500)",
    "system-form-step-text-color-inactive": "#9ca3af",
    "system-form-step-active-shadow": "inset 0 -3px 0 0 var(--color-primary-500)",
    "system-form-step-number-size": "24px",
    "system-form-step-number-radius": "9999px",
    "system-form-step-number-font-size": "14px",
    "system-form-step-number-background-color-inactive": "#e5e7eb",
    "system-form-step-number-color-inactive": "#6b7280",
    "system-form-content-padding": "32px",
    "system-form-form-row-gap": "30px",
    "system-form-form-column-gap": "32px",
    "system-form-field-min-width": "280px",
    "system-form-field-gap": "8px",
    "system-form-field-label-font-size": "14px",
    "system-form-required-color": "#ef4444",
    "system-form-input-border-color": "#d1d5db",
    "system-form-input-text-color": "#0f172a",
    "system-form-textarea-min-height": "104px",
    "system-form-textarea-padding-block": "10px",
    "system-form-counter-font-size": "12px",
    "system-form-error-font-size": "12px",
    "system-form-toggle-row-gap": "48px",
    "system-form-toggle-row-padding-top": "32px",
    "system-form-toggle-row-border": "1px solid var(--table-border-color)",
    "system-form-toggle-min-width": "280px",
    "system-form-actions-padding-top": "24px",
    "system-form-action-button-padding-inline": "16px",
    "system-form-continue-icon-size": "14px",
    "system-form-footer-gap": "12px",
    "system-form-footer-padding-block": "16px",
    "system-form-footer-border": "1px solid var(--table-border-color)",

    // attachment-configuration-form
    "attachment-configuration-section-gap": "24px",
    "attachment-configuration-title-font-size": "20px",
    "attachment-configuration-title-font-weight": "600",
    "attachment-configuration-surface-background-color": "#f9fafb",
    "attachment-configuration-border": "1px solid var(--table-border-color)",
    "attachment-configuration-radius": "8px",
    "attachment-configuration-surface-padding": "24px",
    "attachment-configuration-form-gap": "24px",
    "attachment-configuration-top-column-min-width": "280px",
    "attachment-configuration-top-row-gap": "24px",
    "attachment-configuration-field-gap": "8px",
    "attachment-configuration-description-min-height": "104px",
    "attachment-configuration-icon-row-gap": "12px",
    "attachment-configuration-icon-preview-size": "36px",
    "attachment-configuration-icon-preview-background-color": "#eff6ff",
    "attachment-configuration-icon-size": "18px",
    "attachment-configuration-extension-picker-gap": "8px",
    "attachment-configuration-extension-option-height": "32px",
    "attachment-configuration-extension-option-padding-inline": "12px",
    "attachment-configuration-toggle-padding-top": "12px",
    "attachment-configuration-import-export-gap": "16px",
    "attachment-configuration-action-button-padding-inline": "16px",
    "attachment-configuration-button-content-gap": "8px",
    "attachment-configuration-button-icon-size": "16px",
    "attachment-configuration-empty-state-padding": "24px",
    "attachment-configuration-list-gap": "16px",
    "attachment-configuration-list-max-columns": "3",
    "attachment-configuration-card-min-width": "260px",
    "attachment-configuration-card-max-width": "360px",
    "attachment-configuration-card-padding": "20px",
    "attachment-configuration-card-gap": "16px",
    "attachment-configuration-delete-button-size": "24px",
    "attachment-configuration-card-name-font-size": "16px",
    "attachment-configuration-badge-wrap-padding-bottom": "12px",
    "attachment-configuration-optional-badge-background-color": "#f3f4f6",
    "attachment-configuration-optional-badge-text-color": "#1f2937",
    "attachment-configuration-card-extensions-gap": "12px",
    "attachment-configuration-extension-label-color": "#6b7280",
    "attachment-configuration-extension-badge-height": "20px",
    "attachment-configuration-extension-badge-radius": "9999px",
    "attachment-configuration-extension-badge-padding-inline": "8px",
    "attachment-configuration-extension-badge-background-color": "#f3f4f6",
    "attachment-configuration-extension-badge-text-color": "#6b7280",
    "attachment-configuration-extension-badge-font-size": "10px",
    "attachment-configuration-dialog-list-padding-inline-start": "20px",

    // dashboard-layout
    "size-layout-header": "64px",
    "size-layout-sidebar": "304px",
    "size-layout-sidebar-collapsed": "80px",
    "space-layout-sidebar-items": "16px",
    "border-layout-default": "1px solid var(--border-color)",
    "motion-layout-default": "220ms ease",

    // sidebar
    "sidebar-background-color": "#ffffff",
    "sidebar-item-color": "#677389",
    "sidebar-item-selected-color": THEME_COLOR_PALETTE.primary['500']!,
    "sidebar-item-hover-color": "#ecf2fd",
  }
} as const;
