/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 typing.glb --transform --types 
Files: typing.glb [2.6MB] > C:\Projetos\accesspilot-frontend\public\models\typing-transformed.glb [747.07KB] (71%)
*/

import * as THREE from 'three'
import React, { useEffect, useMemo, useRef } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'typing'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    bigode: THREE.SkinnedMesh
    Boy: THREE.SkinnedMesh
    helmet: THREE.SkinnedMesh
    mixamorigHips: THREE.Bone
  }
  materials: {
    ['MI_Spongebob_Mustache.001']: THREE.MeshStandardMaterial
    ['standardSurface1.001']: THREE.MeshStandardMaterial
    Helmet34: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Typing(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('/models/typing-transformed.glb')
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
  
  useEffect(() => {
    if (actions) {
      // Executa a animação "Idle" por padrão
      actions['typing']?.play()
      console.log(actions)
    }

    return () => {
      if (actions) {
        // Limpa todas as animações ao desmontar o componente
        Object.values(actions).forEach((action) => {
          if (action) action.stop()
        })
      }
    }
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
        </group>
        <skinnedMesh name="bigode" geometry={nodes.bigode.geometry} material={materials['MI_Spongebob_Mustache.001']} skeleton={nodes.bigode.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh castShadow receiveShadow name="Boy" geometry={nodes.Boy.geometry} material={materials['standardSurface1.001']} skeleton={nodes.Boy.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <meshStandardMaterial color={'white'} />
        </skinnedMesh>
        <skinnedMesh name="helmet" geometry={nodes.helmet.geometry} material={materials.Helmet34} skeleton={nodes.helmet.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/typing-transformed.glb')


// import * as THREE from 'three'
// import React, { useRef } from 'react'
// import { Canvas, useGraph } from '@react-three/fiber'
// import { useGLTF, useAnimations, Environment, ContactShadows, OrbitControls } from '@react-three/drei'
// import { GLTF, SkeletonUtils } from 'three-stdlib'
// import { useTheme } from '../layout/ThemeToggle/theme-provider'

// type ActionName = 'typing'

// interface GLTFAction extends THREE.AnimationClip {
//   name: ActionName
// }

// type GLTFResult = GLTF & {
//   nodes: {
//     bigode: THREE.SkinnedMesh
//     Boy: THREE.SkinnedMesh
//     helmet: THREE.SkinnedMesh
//     mixamorigHips: THREE.Bone
//   }
//   materials: {
//     ['MI_Spongebob_Mustache.001']: THREE.MeshStandardMaterial
//     ['standardSurface1.001']: THREE.MeshStandardMaterial
//     Helmet34: THREE.MeshStandardMaterial
//   }
//   animations: GLTFAction[]
// }

// function Character(props: JSX.IntrinsicElements['group']) {
//   const group = useRef<THREE.Group>(null)
//   const { scene, animations } = useGLTF('/models/typing-transformed.glb')
//   const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
//   const { nodes, materials } = useGraph(clone) as GLTFResult
//   const { actions } = useAnimations(animations, group)
//   return (
//     <group ref={group} {...props} dispose={null}>
//       <group name="Scene">
//         <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
//           <primitive object={nodes.mixamorigHips} />
//         </group>
//         <skinnedMesh name="bigode" geometry={nodes.bigode.geometry} material={materials['MI_Spongebob_Mustache.001']} skeleton={nodes.bigode.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
//         <skinnedMesh name="Boy" geometry={nodes.Boy.geometry} material={materials['standardSurface1.001']} skeleton={nodes.Boy.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
//         <skinnedMesh name="helmet" geometry={nodes.helmet.geometry} material={materials.Helmet34} skeleton={nodes.helmet.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
//       </group>
//     </group>
//   )
// }


// export function Typing() {

//   const { theme } = useTheme(); //

//   // apartment, city, dawn, forest, lobby, night, park, studio, sunset, warehouse
//   const environmentHDR = theme === 'dark'
//     ? '/hdr/warehouse.hdr'
//     : theme === 'tangerine'
//     ? '/hdr/lobby.hdr'  // Caminho para o HDR do tema tangerine
//     : '/hdr/park.hdr';  // Tema claro usa o HDR padrão

//   return (
//     <Canvas className="characterForm" camera={{ position: [-1, 2, 10], fov: 25 }}>
      
//       <ambientLight intensity={Math.PI} />
//       <Environment files={environmentHDR} />
//       <Character
//         scale={[0.063, 0.063, 0.063]}
//         position={[0, -1, 0]}
//       />
//       <ContactShadows position={[0, -1.01, 0]} opacity={0.2} scale={10} blur={2} far={10} resolution={256} color="#000000" />
      
//       <OrbitControls />

//     </Canvas>
//   )
// }


// useGLTF.preload('/models/typing-transformed.glb')

