// import React from "react"
// import {
//   AlertCircle,
//   Bell,
//   Calendar,
//   Check,
//   ChevronDown,
//   ChevronsUpDown,
//   Clock,
//   Home,
//   Info,
//   Mail,
//   Settings,
//   User,
//   Activity,
//   Airplay,
//   AlarmCheck,
//   AlarmClock,
//   Album,
//   AlertTriangle,
//   AlignCenter,
//   AlignJustify,
//   AlignLeft,
//   AlignRight,
//   Anchor,
//   Aperture,
//   Archive,
//   ArrowDown,
//   ArrowLeft,
//   ArrowRight,
//   ArrowUp,
//   AtSign,
//   Award,
//   BarChart,
//   Battery,
//   BellOff,
//   Bluetooth,
//   Bold,
//   Book,
//   Bookmark,
//   Box,
//   Briefcase,
//   Camera,
//   Cast,
//   Circle,
//   Clipboard,
//   Cloud,
//   Code,
//   Coffee,
//   Columns,
//   Command,
//   Compass,
//   Copy,
//   CornerDownLeft,
//   CornerDownRight,
//   CornerLeftDown,
//   CornerLeftUp,
//   CornerRightDown,
//   CornerRightUp,
//   CornerUpLeft,
//   CornerUpRight,
//   Cpu,
//   CreditCard,
//   Crop,
//   Crosshair,
//   Database,
//   Delete,
//   Disc,
//   DollarSign,
//   Download,
//   Droplet,
//   Edit,
//   Edit2,
//   Edit3,
//   Eye,
//   EyeOff,
//   Facebook,
//   FastForward,
//   Feather,
//   File,
//   FileMinus,
//   FilePlus,
//   FileText,
//   Film,
//   Filter,
//   Flag,
//   Folder,
//   FolderMinus,
//   FolderPlus,
//   Frown,
//   Gift,
//   GitBranch,
//   GitCommit,
//   GitMerge,
//   GitPullRequest,
//   Globe,
//   Grid,
//   HardDrive,
//   Hash,
//   Headphones,
//   Heart,
//   HelpCircle,
//   Image,
//   Inbox,
//   Instagram,
//   Key,
//   Layers,
//   Layout,
//   LifeBuoy,
//   Link,
//   Link2,
//   Linkedin,
//   List,
//   Loader,
//   Lock,
//   LogIn,
//   LogOut,
//   Map,
//   MapPin,
//   Maximize,
//   Maximize2,
//   Meh,
//   Menu,
//   MessageCircle,
//   MessageSquare,
//   Mic,
//   MicOff,
//   Minimize,
//   Minimize2,
//   Minus,
//   Monitor,
//   Moon,
//   MoreHorizontal,
//   MoreVertical,
//   Move,
//   Music,
//   Navigation,
//   Navigation2,
//   Octagon,
//   Package,
//   Paperclip,
//   Pause,
//   PauseCircle,
//   Percent,
//   Phone,
//   PhoneCall,
//   PhoneForwarded,
//   PhoneIncoming,
//   PhoneMissed,
//   PhoneOff,
//   PhoneOutgoing,
//   PieChart,
//   Play,
//   PlayCircle,
//   Plus,
//   PlusCircle,
//   PlusSquare,
//   Pocket,
//   Power,
//   Printer,
//   Radio,
//   RefreshCcw,
//   RefreshCw,
//   Repeat,
//   Rewind,
//   RotateCcw,
//   RotateCw,
//   Rss,
//   Save,
//   Scissors,
//   Search,
//   Send,
//   Server,
//   Share,
//   Share2,
//   Shield,
//   ShieldOff,
//   ShoppingBag,
//   ShoppingCart,
//   Shuffle,
//   Sidebar,
//   SkipBack,
//   SkipForward,
//   Slack,
//   Slash,
//   Sliders,
//   Smartphone,
//   Smile,
//   Speaker,
//   Square,
//   Star,
//   StopCircle,
//   Sun,
//   Sunrise,
//   Sunset,
//   Tablet,
//   Tag,
//   Target,
//   Terminal,
//   Thermometer,
//   ThumbsDown,
//   ThumbsUp,
//   ToggleLeft,
//   ToggleRight,
//   PenToolIcon as Tool,
//   Trash,
//   Trash2,
//   Trello,
//   TrendingDown,
//   TrendingUp,
//   Triangle,
//   Truck,
//   Tv,
//   Twitter,
//   Type,
//   Umbrella,
//   Underline,
//   Unlock,
//   Upload,
//   UploadCloud,
//   UserCheck,
//   UserMinus,
//   UserPlus,
//   UserX,
//   Video,
//   VideoOff,
//   Voicemail,
//   Volume,
//   Volume1,
//   Volume2,
//   VolumeX,
//   Watch,
//   Wifi,
//   WifiOff,
//   Wind,
//   X,
//   XCircle,
//   XSquare,
//   Youtube,
//   Zap,
//   ZapOff,
//   ZoomIn,
//   ZoomOut,
// } from "lucide-react"

// const iconMap = {
//   AlertCircle,
//   Bell,
//   Calendar,
//   Check,
//   ChevronDown,
//   ChevronsUpDown,
//   Clock,
//   Home,
//   Info,
//   Mail,
//   Settings,
//   User,
//   Activity,
//   Airplay,
//   AlarmCheck,
//   AlarmClock,
//   Album,
//   AlertTriangle,
//   AlignCenter,
//   AlignJustify,
//   AlignLeft,
//   AlignRight,
//   Anchor,
//   Aperture,
//   Archive,
//   ArrowDown,
//   ArrowLeft,
//   ArrowRight,
//   ArrowUp,
//   AtSign,
//   Award,
//   BarChart,
//   Battery,
//   BellOff,
//   Bluetooth,
//   Bold,
//   Book,
//   Bookmark,
//   Box,
//   Briefcase,
//   Camera,
//   Cast,
//   Circle,
//   Clipboard,
//   Cloud,
//   Code,
//   Coffee,
//   Columns,
//   Command,
//   Compass,
//   Copy,
//   CornerDownLeft,
//   CornerDownRight,
//   CornerLeftDown,
//   CornerLeftUp,
//   CornerRightDown,
//   CornerRightUp,
//   CornerUpLeft,
//   CornerUpRight,
//   Cpu,
//   CreditCard,
//   Crop,
//   Crosshair,
//   Database,
//   Delete,
//   Disc,
//   DollarSign,
//   Download,
//   Droplet,
//   Edit,
//   Edit2,
//   Edit3,
//   Eye,
//   EyeOff,
//   Facebook,
//   FastForward,
//   Feather,
//   File,
//   FileMinus,
//   FilePlus,
//   FileText,
//   Film,
//   Filter,
//   Flag,
//   Folder,
//   FolderMinus,
//   FolderPlus,
//   Frown,
//   Gift,
//   GitBranch,
//   GitCommit,
//   GitMerge,
//   GitPullRequest,
//   Globe,
//   Grid,
//   HardDrive,
//   Hash,
//   Headphones,
//   Heart,
//   HelpCircle,
//   Image,
//   Inbox,
//   Instagram,
//   Key,
//   Layers,
//   Layout,
//   LifeBuoy,
//   Link,
//   Link2,
//   Linkedin,
//   List,
//   Loader,
//   Lock,
//   LogIn,
//   LogOut,
//   Map,
//   MapPin,
//   Maximize,
//   Maximize2,
//   Meh,
//   Menu,
//   MessageCircle,
//   MessageSquare,
//   Mic,
//   MicOff,
//   Minimize,
//   Minimize2,
//   Minus,
//   Monitor,
//   Moon,
//   MoreHorizontal,
//   MoreVertical,
//   Move,
//   Music,
//   Navigation,
//   Navigation2,
//   Octagon,
//   Package,
//   Paperclip,
//   Pause,
//   PauseCircle,
//   Percent,
//   Phone,
//   PhoneCall,
//   PhoneForwarded,
//   PhoneIncoming,
//   PhoneMissed,
//   PhoneOff,
//   PhoneOutgoing,
//   PieChart,
//   Play,
//   PlayCircle,
//   Plus,
//   PlusCircle,
//   PlusSquare,
//   Pocket,
//   Power,
//   Printer,
//   Radio,
//   RefreshCcw,
//   RefreshCw,
//   Repeat,
//   Rewind,
//   RotateCcw,
//   RotateCw,
//   Rss,
//   Save,
//   Scissors,
//   Search,
//   Send,
//   Server,
//   Share,
//   Share2,
//   Shield,
//   ShieldOff,
//   ShoppingBag,
//   ShoppingCart,
//   Shuffle,
//   Sidebar,
//   SkipBack,
//   SkipForward,
//   Slack,
//   Slash,
//   Sliders,
//   Smartphone,
//   Smile,
//   Speaker,
//   Square,
//   Star,
//   StopCircle,
//   Sun,
//   Sunrise,
//   Sunset,
//   Tablet,
//   Tag,
//   Target,
//   Terminal,
//   Thermometer,
//   ThumbsDown,
//   ThumbsUp,
//   ToggleLeft,
//   ToggleRight,
//   Tool,
//   Trash,
//   Trash2,
//   Trello,
//   TrendingDown,
//   TrendingUp,
//   Triangle,
//   Truck,
//   Tv,
//   Twitter,
//   Type,
//   Umbrella,
//   Underline,
//   Unlock,
//   Upload,
//   UploadCloud,
//   UserCheck,
//   UserMinus,
//   UserPlus,
//   UserX,
//   Video,
//   VideoOff,
//   Voicemail,
//   Volume,
//   Volume1,
//   Volume2,
//   VolumeX,
//   Watch,
//   Wifi,
//   WifiOff,
//   Wind,
//   X,
//   XCircle,
//   XSquare,
//   Youtube,
//   Zap,
//   ZapOff,
//   ZoomIn,
//   ZoomOut,
// }

// type IconListProps = {
//   value: string
//   onChange: (iconName: string) => void
// }

// export function IconList({ value, onChange }: IconListProps) {
//   return (
//     <div className="grid grid-cols-8 gap-2 max-h-[400px] overflow-y-auto p-2 border rounded">
//       {Object.entries(iconMap).map(([name, Icon]) => (
//         <button
//           key={name}
//           type="button"
//           className={`flex flex-col items-center justify-center p-1 border rounded hover:bg-gray-100 ${
//             value === name ? "bg-blue-100 border-blue-500" : ""
//           }`}
//           onClick={() => onChange(name)}
//         >
//           <Icon className="w-5 h-5 mb-1" />
//           <span className="text-[10px] truncate w-full text-center">{name}</span>
//         </button>
//       ))}
//     </div>
//   )
// }



import React, { useState } from "react"
import { iconMap, getIconByName } from "../../utils/IconUtils"
import { Input } from "../../components/ui/input"

type IconListProps = {
  value: string
  onChange: (iconName: string) => void
}

export function IconList({ value, onChange }: IconListProps) {
  const [searchTerm, setSearchTerm] = useState("")

  const filteredIcons = iconMap.filter(([name]) => name.toLowerCase().includes(searchTerm.toLowerCase()))

  return (
    <div className="space-y-2">
      <Input
        type="text"
        placeholder="Pesquisar ícones..."
        value={searchTerm}
        onChange={(e) => setSearchTerm(e.target.value)}
        className="mb-2"
      />
      <div className="grid grid-cols-8 gap-2 max-h-[400px] overflow-y-auto p-2 border rounded">
        {filteredIcons.map(([name, Icon]) => (
          <button
            key={name}
            type="button"
            className={`flex flex-col items-center justify-center p-1 border rounded hover:bg-gray-100 ${
              value === name ? "bg-blue-100 border-blue-500" : ""
            }`}
            onClick={() => onChange(name)}
          >
            <Icon className="w-5 h-5 mb-1" />
            <span className="text-[10px] truncate w-full text-center">{name}</span>
          </button>
        ))}
      </div>
    </div>
  )
}


